### ISSUE TITLE
Eg 009 issues

### ISSUE THREAD

**Issue by Ricoch** [docusign/eg-03-ruby-auth-code-grant#1] opened 2019-08-14 19:10 UTC
Hello everyone, I am new to DocuSign and I am trying to send an envelope using a template on the server. I was trying to use the example 009 to see how this was done, but the example itself does not seem to be working, I get a `Bad request` error and that's all.

https://github.com/docusign/eg-03-ruby-auth-code-grant/blob/master/app/controllers/eg009_use_template_controller.rb

![image](https://user-images.githubusercontent.com/42209955/63048961-050f8180-beae-11e9-8527-f647a307cbb3.png)
![image](https://user-images.githubusercontent.com/42209955/63048988-0fca1680-beae-11e9-8b81-8a67807f5b48.png)

**Comment by LarryKlugerDS** [comment] 2019-08-14 19:15
Did you first run the eg008 workflow to create the template on your DocuSign account? 
I will also ask the examples manager to assist.

**Comment by LarryKlugerDS** [comment] 2019-08-14 19:21
I have submitted internal ticket DEVDOCS-1294.
Do the other workflows work for you? 
Thanks,
Larry

**Comment by Ricoch** [comment] 2019-08-14 19:43
Hello @LarryKlugerDS, thanks for coming back.

I did not do the flow on eg008 because I had already manually created the template on DocuSign sandbox, this is the template_id I got from DocuSign sandbox:
![image](https://user-images.githubusercontent.com/42209955/63050850-69ccdb00-beb2-11e9-84ff-1ff5afa6ae9b.png)

And this is the variable with the value on my code:
![image](https://user-images.githubusercontent.com/42209955/63050898-8701a980-beb2-11e9-8a61-8cbfb6d0ea84.png)

Do I 100% need to create the template programmatically for this to work?

**Comment by LarryKlugerDS** [comment] 2019-08-14 20:06
Ohh, now I understand: you are modifying the workflow 9 code and it is not working. 
Yes, of course you are able to do that and should be able to do it.

>Re: Do I 100% need to create the template programmatically for this to work? 

No, you should be able to create the template from the web too and then send an envelope via the API which uses the API. It is a common flow to do so.

The first question is did un-modified examples 8 and 9 work properly? If they did then the problem is in your modifications. If they did not work then the problem is in the tool....

You should also look at the API log to understand exactly what is happening. See https://support.docusign.com/en/guides/ndse-user-guide-api-request-logging

**Comment by Ricoch** [comment] 2019-08-14 20:22
I did not modify eg 009, if you compare the image I pasted it is the same `worker` and `make_envelope` methods. The only thing I modified is how I am charging the `template_id` variable, have a look:

Github code:
![image](https://user-images.githubusercontent.com/42209955/63053195-99321680-beb7-11e9-89f8-69d78034a3c8.png)

My code:
![image](https://user-images.githubusercontent.com/42209955/63053223-a949f600-beb7-11e9-88fa-fa01edc789e7.png)

as you can see, I even left the comments.

In any case, I tried doing the API call via postman with the same JSON I got from the cURL example here: https://developers.docusign.com/esign-rest-api/code-examples/code-example-use-template and I am getting the following response:

![image](https://user-images.githubusercontent.com/42209955/63053340-ed3cfb00-beb7-11e9-9461-b2ffd9c16cfb.png)

**Comment by LarryKlugerDS** [comment] 2019-12-02 10:37
Hi @Ricoch , I tried to duplicate your problem, but when I:

1. Downloaded, installed, configured, ran the repo
1. Ran example 8 to create the template
1. Ran example 9 to use the template

...everything worked fine.

I will be closing this issue as can't reproduce. If you're still having questions, please use our StackOverflow community -- tag your question with `docusignapi` If you have a support contract with DocuSign, ask for developer support.

**Closed by LarryKlugerDS** 2019-12-02 10:37 UTC
Labels: DEVDOCS-1294, answered, question
